### ISSUE TITLE
Compiled .js remains if its relative .coffee is deleted.

### ISSUE THREAD

**Issue by davidglivar** [Sutto/barista#53] opened 2011-08-18 23:59 UTC
I think the title says it all. Has anyone else ran into this issue?

EDIT: 
rails 3.0.9, using with Jammit

**Comment by Sutto** [comment] 2011-09-03 15:02
Sorry for the belated response David,

This is by design - because it's possible for users to also have static js / to compile into directories containing JS already, and since Barista doesn't strictly track files it compiled, we can't (currently atleast) track file deletions. The assumption being it's up to the developer.

I hope you don't mind, but I'm going to close this for the moment - Namely, I think it's more a matter of user behavior rather than application behaviour. Feel free to reopen if you'd like to give reasons why it should track deletions.

-- Darcy

**Closed as completed by Sutto** 2011-09-03 15:02 UTC
